name: rdl-mid2gpkg
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=21.2.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2021.4.13
  - cairo=1.16.0
  - certifi=2020.12.5
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - colorama=0.4.4
  - curl=7.76.1
  - expat=2.4.1
  - fiona=1.8.18
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.2.1
  - geopandas=0.9.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - intel-openmp=2021.2.0
  - jpeg=9d
  - kealib=1.4.14
  - krb5=1.19.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.1
  - libffi=3.3
  - libgdal=3.2.1
  - libglib=2.68.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - mkl=2021.2.0
  - munch=2.5.0
  - numpy=1.20.3
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.2.4
  - pcre=8.44
  - pip=21.1.2
  - pixman=0.40.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=7.2.0
  - pygeos=0.10
  - pyparsing=2.4.7
  - pyproj=3.0.1
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - rasterio=1.2.3
  - rtree=0.9.4
  - setuptools=52.0.0
  - shapely=1.7.1
  - shellingham=1.4.0
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.35.5
  - tbb=2021.2.0
  - tiledb=2.2.9
  - tk=8.6.10
  - tqdm=4.61.0
  - typer=0.3.2
  - tzdata=2021a
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - wincertstore=0.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - bcj-cffi==0.5.1
    - brotli==1.0.9
    - cffi==1.14.5
    - multivolumefile==0.2.3
    - py7zr==0.16.1
    - pycparser==2.20
    - pycryptodomex==3.10.1
    - pyppmd==0.15.0
    - pyzstd==0.14.4
    - texttable==1.6.3
